<?php

namespace JPG\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends EntityRepository
{
}
