<?php

namespace JPG\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LunchRepository extends EntityRepository
{
}
